### PR TITLE
Added printing releaseUrl feature

### PR DESCRIPTION
**Pull request by konstzv**
Added possibility to enable/disable printing releaseUrl of uploaded application

### CODE REVIEW

**Comment by oliviergauthier** [comment]
Do you really need to hide this url ? Why not always show it at the end of the upload ? Is it only for debug or you use it in your build process ?

**Comment by konstzv** [comment]
> Do you really need to hide this url ? Why not always show it at the end of the upload ? Is it only for debug or you use it in your build process ?

 Thank you for the quick response. I don't get it a little bit.
 In my case, users build application on their personal computers and and they want get a link when the download is successful. 
 Do you doubt that feature should be disabled by default? I can change the initial state to enabled(true) - it's even more convenient for me. I disabled it by default because I thought it can interfere with someone.
 Or you do you think feature should be enabled always and we don't need flag to control it? That's fine with me, just wanted to make it more flexible.
 Let me know which option is better - I will make changes.

**Comment by konstzv** [comment]
> I think we can always print url and wait for someone asks to hide it :-)
Ok) I removed flag

**Comment by konstzv** [comment]
@oliviergauthier is it ok? Can you merge it?

**Pull request merged**
